// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjlnbatkafnwfkjufdll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbG5iYXRrYWZud2ZranVmZGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDk1ODAsImV4cCI6MjA2MDEyNTU4MH0.NxWfA3GzrYCZkvK3K02rkN1Y4V9dQv5PHVW77E1hkWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);